/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatBalanceteRouteImport } from './routes/api/chat-balancete'
import { Route as AuthenticatedResultadoFinanceiroRouteImport } from './routes/_authenticated/resultado-financeiro'
import { Route as AuthenticatedDespAdmRouteImport } from './routes/_authenticated/desp-adm'
import { Route as AuthenticatedBpDreRouteImport } from './routes/_authenticated/bp-dre'
import { Route as AuthenticatedBalanceteGerencialRouteImport } from './routes/_authenticated/balancete-gerencial'
import { Route as AuthenticatedAnaliseDespesasAdmRouteImport } from './routes/_authenticated/analise-despesas-adm'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedAdminPendenciasRouteImport } from './routes/_authenticated/_admin/pendencias'
import { Route as AuthenticatedAdminPainelRouteImport } from './routes/_authenticated/_admin/painel'
import { Route as AuthenticatedAdminImportarRouteImport } from './routes/_authenticated/_admin/importar'
import { Route as AuthenticatedAdminDeparaRouteImport } from './routes/_authenticated/_admin/depara'
import { Route as AuthenticatedAdminControleUsuariosRouteImport } from './routes/_authenticated/_admin/controle-usuarios'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/_admin/configuracoes'
import { Route as AuthenticatedAdminBpDreImportarRouteImport } from './routes/_authenticated/_admin/bp-dre-importar'
import { Route as AuthenticatedAdminBpDreDeparaRouteImport } from './routes/_authenticated/_admin/bp-dre-depara'
import { Route as AuthenticatedAdminBalanceteRouteImport } from './routes/_authenticated/_admin/balancete'
import { Route as AuthenticatedAdminAjustesRouteImport } from './routes/_authenticated/_admin/ajustes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatBalanceteRoute = ApiChatBalanceteRouteImport.update({
  id: '/api/chat-balancete',
  path: '/api/chat-balancete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResultadoFinanceiroRoute =
  AuthenticatedResultadoFinanceiroRouteImport.update({
    id: '/resultado-financeiro',
    path: '/resultado-financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespAdmRoute = AuthenticatedDespAdmRouteImport.update({
  id: '/desp-adm',
  path: '/desp-adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBpDreRoute = AuthenticatedBpDreRouteImport.update({
  id: '/bp-dre',
  path: '/bp-dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBalanceteGerencialRoute =
  AuthenticatedBalanceteGerencialRouteImport.update({
    id: '/balancete-gerencial',
    path: '/balancete-gerencial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnaliseDespesasAdmRoute =
  AuthenticatedAnaliseDespesasAdmRouteImport.update({
    id: '/analise-despesas-adm',
    path: '/analise-despesas-adm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPendenciasRoute =
  AuthenticatedAdminPendenciasRouteImport.update({
    id: '/pendencias',
    path: '/pendencias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPainelRoute =
  AuthenticatedAdminPainelRouteImport.update({
    id: '/painel',
    path: '/painel',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportarRoute =
  AuthenticatedAdminImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeparaRoute =
  AuthenticatedAdminDeparaRouteImport.update({
    id: '/depara',
    path: '/depara',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminControleUsuariosRoute =
  AuthenticatedAdminControleUsuariosRouteImport.update({
    id: '/controle-usuarios',
    path: '/controle-usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBpDreImportarRoute =
  AuthenticatedAdminBpDreImportarRouteImport.update({
    id: '/bp-dre-importar',
    path: '/bp-dre-importar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBpDreDeparaRoute =
  AuthenticatedAdminBpDreDeparaRouteImport.update({
    id: '/bp-dre-depara',
    path: '/bp-dre-depara',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBalanceteRoute =
  AuthenticatedAdminBalanceteRouteImport.update({
    id: '/balancete',
    path: '/balancete',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAjustesRoute =
  AuthenticatedAdminAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/analise-despesas-adm': typeof AuthenticatedAnaliseDespesasAdmRoute
  '/balancete-gerencial': typeof AuthenticatedBalanceteGerencialRoute
  '/bp-dre': typeof AuthenticatedBpDreRoute
  '/desp-adm': typeof AuthenticatedDespAdmRoute
  '/resultado-financeiro': typeof AuthenticatedResultadoFinanceiroRoute
  '/api/chat-balancete': typeof ApiChatBalanceteRoute
  '/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/balancete': typeof AuthenticatedAdminBalanceteRoute
  '/bp-dre-depara': typeof AuthenticatedAdminBpDreDeparaRoute
  '/bp-dre-importar': typeof AuthenticatedAdminBpDreImportarRoute
  '/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/controle-usuarios': typeof AuthenticatedAdminControleUsuariosRoute
  '/depara': typeof AuthenticatedAdminDeparaRoute
  '/importar': typeof AuthenticatedAdminImportarRoute
  '/painel': typeof AuthenticatedAdminPainelRoute
  '/pendencias': typeof AuthenticatedAdminPendenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/analise-despesas-adm': typeof AuthenticatedAnaliseDespesasAdmRoute
  '/balancete-gerencial': typeof AuthenticatedBalanceteGerencialRoute
  '/bp-dre': typeof AuthenticatedBpDreRoute
  '/desp-adm': typeof AuthenticatedDespAdmRoute
  '/resultado-financeiro': typeof AuthenticatedResultadoFinanceiroRoute
  '/api/chat-balancete': typeof ApiChatBalanceteRoute
  '/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/balancete': typeof AuthenticatedAdminBalanceteRoute
  '/bp-dre-depara': typeof AuthenticatedAdminBpDreDeparaRoute
  '/bp-dre-importar': typeof AuthenticatedAdminBpDreImportarRoute
  '/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/controle-usuarios': typeof AuthenticatedAdminControleUsuariosRoute
  '/depara': typeof AuthenticatedAdminDeparaRoute
  '/importar': typeof AuthenticatedAdminImportarRoute
  '/painel': typeof AuthenticatedAdminPainelRoute
  '/pendencias': typeof AuthenticatedAdminPendenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/analise-despesas-adm': typeof AuthenticatedAnaliseDespesasAdmRoute
  '/_authenticated/balancete-gerencial': typeof AuthenticatedBalanceteGerencialRoute
  '/_authenticated/bp-dre': typeof AuthenticatedBpDreRoute
  '/_authenticated/desp-adm': typeof AuthenticatedDespAdmRoute
  '/_authenticated/resultado-financeiro': typeof AuthenticatedResultadoFinanceiroRoute
  '/api/chat-balancete': typeof ApiChatBalanceteRoute
  '/_authenticated/_admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/_authenticated/_admin/balancete': typeof AuthenticatedAdminBalanceteRoute
  '/_authenticated/_admin/bp-dre-depara': typeof AuthenticatedAdminBpDreDeparaRoute
  '/_authenticated/_admin/bp-dre-importar': typeof AuthenticatedAdminBpDreImportarRoute
  '/_authenticated/_admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/_admin/controle-usuarios': typeof AuthenticatedAdminControleUsuariosRoute
  '/_authenticated/_admin/depara': typeof AuthenticatedAdminDeparaRoute
  '/_authenticated/_admin/importar': typeof AuthenticatedAdminImportarRoute
  '/_authenticated/_admin/painel': typeof AuthenticatedAdminPainelRoute
  '/_authenticated/_admin/pendencias': typeof AuthenticatedAdminPendenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/analise-despesas-adm'
    | '/balancete-gerencial'
    | '/bp-dre'
    | '/desp-adm'
    | '/resultado-financeiro'
    | '/api/chat-balancete'
    | '/ajustes'
    | '/balancete'
    | '/bp-dre-depara'
    | '/bp-dre-importar'
    | '/configuracoes'
    | '/controle-usuarios'
    | '/depara'
    | '/importar'
    | '/painel'
    | '/pendencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/analise-despesas-adm'
    | '/balancete-gerencial'
    | '/bp-dre'
    | '/desp-adm'
    | '/resultado-financeiro'
    | '/api/chat-balancete'
    | '/ajustes'
    | '/balancete'
    | '/bp-dre-depara'
    | '/bp-dre-importar'
    | '/configuracoes'
    | '/controle-usuarios'
    | '/depara'
    | '/importar'
    | '/painel'
    | '/pendencias'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aguardando-aprovacao'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/analise-despesas-adm'
    | '/_authenticated/balancete-gerencial'
    | '/_authenticated/bp-dre'
    | '/_authenticated/desp-adm'
    | '/_authenticated/resultado-financeiro'
    | '/api/chat-balancete'
    | '/_authenticated/_admin/ajustes'
    | '/_authenticated/_admin/balancete'
    | '/_authenticated/_admin/bp-dre-depara'
    | '/_authenticated/_admin/bp-dre-importar'
    | '/_authenticated/_admin/configuracoes'
    | '/_authenticated/_admin/controle-usuarios'
    | '/_authenticated/_admin/depara'
    | '/_authenticated/_admin/importar'
    | '/_authenticated/_admin/painel'
    | '/_authenticated/_admin/pendencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  AuthRoute: typeof AuthRoute
  ApiChatBalanceteRoute: typeof ApiChatBalanceteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-balancete': {
      id: '/api/chat-balancete'
      path: '/api/chat-balancete'
      fullPath: '/api/chat-balancete'
      preLoaderRoute: typeof ApiChatBalanceteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resultado-financeiro': {
      id: '/_authenticated/resultado-financeiro'
      path: '/resultado-financeiro'
      fullPath: '/resultado-financeiro'
      preLoaderRoute: typeof AuthenticatedResultadoFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desp-adm': {
      id: '/_authenticated/desp-adm'
      path: '/desp-adm'
      fullPath: '/desp-adm'
      preLoaderRoute: typeof AuthenticatedDespAdmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bp-dre': {
      id: '/_authenticated/bp-dre'
      path: '/bp-dre'
      fullPath: '/bp-dre'
      preLoaderRoute: typeof AuthenticatedBpDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balancete-gerencial': {
      id: '/_authenticated/balancete-gerencial'
      path: '/balancete-gerencial'
      fullPath: '/balancete-gerencial'
      preLoaderRoute: typeof AuthenticatedBalanceteGerencialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise-despesas-adm': {
      id: '/_authenticated/analise-despesas-adm'
      path: '/analise-despesas-adm'
      fullPath: '/analise-despesas-adm'
      preLoaderRoute: typeof AuthenticatedAnaliseDespesasAdmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/pendencias': {
      id: '/_authenticated/_admin/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedAdminPendenciasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/painel': {
      id: '/_authenticated/_admin/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedAdminPainelRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/importar': {
      id: '/_authenticated/_admin/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedAdminImportarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/depara': {
      id: '/_authenticated/_admin/depara'
      path: '/depara'
      fullPath: '/depara'
      preLoaderRoute: typeof AuthenticatedAdminDeparaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/controle-usuarios': {
      id: '/_authenticated/_admin/controle-usuarios'
      path: '/controle-usuarios'
      fullPath: '/controle-usuarios'
      preLoaderRoute: typeof AuthenticatedAdminControleUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/configuracoes': {
      id: '/_authenticated/_admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/bp-dre-importar': {
      id: '/_authenticated/_admin/bp-dre-importar'
      path: '/bp-dre-importar'
      fullPath: '/bp-dre-importar'
      preLoaderRoute: typeof AuthenticatedAdminBpDreImportarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/bp-dre-depara': {
      id: '/_authenticated/_admin/bp-dre-depara'
      path: '/bp-dre-depara'
      fullPath: '/bp-dre-depara'
      preLoaderRoute: typeof AuthenticatedAdminBpDreDeparaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/balancete': {
      id: '/_authenticated/_admin/balancete'
      path: '/balancete'
      fullPath: '/balancete'
      preLoaderRoute: typeof AuthenticatedAdminBalanceteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/ajustes': {
      id: '/_authenticated/_admin/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAdminAjustesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAjustesRoute: typeof AuthenticatedAdminAjustesRoute
  AuthenticatedAdminBalanceteRoute: typeof AuthenticatedAdminBalanceteRoute
  AuthenticatedAdminBpDreDeparaRoute: typeof AuthenticatedAdminBpDreDeparaRoute
  AuthenticatedAdminBpDreImportarRoute: typeof AuthenticatedAdminBpDreImportarRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminControleUsuariosRoute: typeof AuthenticatedAdminControleUsuariosRoute
  AuthenticatedAdminDeparaRoute: typeof AuthenticatedAdminDeparaRoute
  AuthenticatedAdminImportarRoute: typeof AuthenticatedAdminImportarRoute
  AuthenticatedAdminPainelRoute: typeof AuthenticatedAdminPainelRoute
  AuthenticatedAdminPendenciasRoute: typeof AuthenticatedAdminPendenciasRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAjustesRoute: AuthenticatedAdminAjustesRoute,
    AuthenticatedAdminBalanceteRoute: AuthenticatedAdminBalanceteRoute,
    AuthenticatedAdminBpDreDeparaRoute: AuthenticatedAdminBpDreDeparaRoute,
    AuthenticatedAdminBpDreImportarRoute: AuthenticatedAdminBpDreImportarRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminControleUsuariosRoute:
      AuthenticatedAdminControleUsuariosRoute,
    AuthenticatedAdminDeparaRoute: AuthenticatedAdminDeparaRoute,
    AuthenticatedAdminImportarRoute: AuthenticatedAdminImportarRoute,
    AuthenticatedAdminPainelRoute: AuthenticatedAdminPainelRoute,
    AuthenticatedAdminPendenciasRoute: AuthenticatedAdminPendenciasRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAnaliseDespesasAdmRoute: typeof AuthenticatedAnaliseDespesasAdmRoute
  AuthenticatedBalanceteGerencialRoute: typeof AuthenticatedBalanceteGerencialRoute
  AuthenticatedBpDreRoute: typeof AuthenticatedBpDreRoute
  AuthenticatedDespAdmRoute: typeof AuthenticatedDespAdmRoute
  AuthenticatedResultadoFinanceiroRoute: typeof AuthenticatedResultadoFinanceiroRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAnaliseDespesasAdmRoute: AuthenticatedAnaliseDespesasAdmRoute,
  AuthenticatedBalanceteGerencialRoute: AuthenticatedBalanceteGerencialRoute,
  AuthenticatedBpDreRoute: AuthenticatedBpDreRoute,
  AuthenticatedDespAdmRoute: AuthenticatedDespAdmRoute,
  AuthenticatedResultadoFinanceiroRoute: AuthenticatedResultadoFinanceiroRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  AuthRoute: AuthRoute,
  ApiChatBalanceteRoute: ApiChatBalanceteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
